## Service documentation https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
apiVersion: v1
kind: Service
metadata:
  name: rssfeedpuller-service

spec:
  selector:  # Selector routes service traffic to pods with the label keys and values that match this selector.
    app: rssfeedpuller

  ports:
    - name: http-port
      protocol: TCP
      port: 6020  # This is the external port that is used to access the service.
      targetPort: 6020  # This port was defined as the container port in the Dockerfile
      # nodePort: 30080
  
  type: ClusterIP  # Need to use NodePort as it is the only one that allows for external access.